### ISSUE TITLE
Period error for Semiannual data

### ISSUE THREAD

**Issue by wochner** [bpsmith/tia#18]
I think the period specification for semiannual data should be 'SEMI_ANNUALLY'. 'SEMI-ANNUAL' gives me an error:

Traceback (most recent call last):
  File "F:\source\Python\macro\macro_sheet_financial.py", line 64, in <module>
    non_trading_day_fill_option = 'ALL_CALENDAR_DAYS')
  File "C:\Python27\lib\site-packages\tia\bbg\v3api.py", line 740, in get_historical
    return self.execute(req)
  File "C:\Python27\lib\site-packages\tia\bbg\v3api.py", line 716, in execute
    asbbg = request.get_bbg_request(svc, session)
  File "C:\Python27\lib\site-packages\tia\bbg\v3api.py", line 346, in get_bbg_request
    request.set('periodicitySelection', self.period)
  File "C:\Python27\lib\site-packages\blpapi\request.py", line 61, in set
    self.asElement().setElement(name, value)
  File "C:\Python27\lib\site-packages\blpapi\element.py", line 640, in setElement
    traits[0](self.__handle, name[0], name[1], value))
  File "C:\Python27\lib\site-packages\blpapi\exception.py", line 145, in raiseOnError
    _ExceptionUtil.raiseException(errorCode, description)
  File "C:\Python27\lib\site-packages\blpapi\exception.py", line 137, in raiseException
    raise errorClass(description, errorCode)
NotFoundException: Constant with value 'SEMI-ANNUAL' does not exist. (0x0006000d)

**Comment by jason79** [comment]
I've tried "SEMI-ANNUALLY" ... but it doesn't work  

File "C:\Python27\lib\site-packages\blpapi\exception.py", line 137, in raiseException
    raise errorClass(description, errorCode)
NotFoundException: Constant with value 'SEMI-ANNUALLY' does not exist. (0x0006000d)

Where to look this up?

**Comment by wochner** [comment]
Should be with underscore, not dash. I.e. "SEMI_ANNUALLY". Reference is on page 166 of the v3 developers guide. Excerpt below.
