### ISSUE TITLE
importing tia.bbg.datamanager......SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by MichJim** [bpsmith/tia#26]
I type

import pandas as pd
import tia.bbg.datamgr as dm

and get the error above

Full error message below
What should I do?

Traceback (most recent call last):

  File "/Users/michaelspencer/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-129e848df133>", line 2, in <module>
    import tia.bbg.datamgr as dm

  File "/Users/michaelspencer/miniconda3/lib/python3.6/site-packages/tia/bbg/__init__.py", line 1, in <module>
    from tia.bbg.v3api import *

  File "/Users/michaelspencer/miniconda3/lib/python3.6/site-packages/tia/bbg/v3api.py", line 186
    print 'unhandled event: %s' % evt.EventType
                              ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by STguerin** [comment]
you should try to run it on python 2.7 instead of python 3

**Comment by MichJim** [comment]
thanks

**Comment by MichJim** [comment]
changed my python to 2.7, installed tia in the new environment and now get

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-129e848df133> in <module>()
      1 import pandas as pd
----> 2 import tia.bbg.datamgr as dm

ImportError: No module named tia.bbg.datamgr

**Comment by MichJim** [comment]
Looks like tia not installed properly
