### ISSUE TITLE
Missing tia/analysis/model subfolder [Anaconda3/Python 3.6]

### ISSUE THREAD

**Issue by acmadmin** [bpsmith/tia#35]
I installed using "pip install tia" from Anaconda3/Scripts (i.e. Anaconda's pip) and can see the package installed in Lib/site-packages/tia. However the subfolder tia/analysis/model is missing. 

When I try to use "import tia.analysis.model as model", I get the following error:

import tia.analysis.model as model
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-c341cb7edf03>", line 1, in <module>
    import tia.analysis.model as model
  File "C:\Program Files\JetBrains\PyCharm Edu 4.0.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tia\analysis\__init__.py", line 2, in <module>
    from tia.analysis.model import *

**Comment by summerside182** [comment]
tia is not implemented for python 3

**Comment by acmadmin** [comment]
Thanks. Found this link in the issues #11 that seems to work well. 

https://github.com/PaulMest/tia/
